pkg/validations/requests_limits.go

fix gofmt issue

---

pkg/validations/base.go
pkg/validations/replicas.go
pkg/validations/requests_limits.go

Remove non-used validations with client code

---

Makefile
cmd/manager/main.go
config/config.go
go.mod
go.sum
pkg/controller/controller.go
pkg/controller/generic_reconciler.go
pkg/controller/generic_reconciler_test.go
pkg/testutils/templates/Deployment.yaml.tpl
pkg/testutils/templates/ReplicaSet.yaml.tpl
pkg/testutils/testutils.go
pkg/validations/base.go
pkg/validations/base_test.go
pkg/validations/replicas.go
pkg/validations/replicas_test.go
pkg/validations/requests_limits.go
pkg/validations/requests_limits_test.go
pkg/validations/utils.go

* Added unit tests
* Unified some function's signatures when they're similar
* Change some of them to make them easier to test
* Make sure prometheus metrics are added only once
* `testutils` library could get more work to make it more generic, but it should be enough for the moment

Added unit tests

---

build_deploy.sh
pr_check.sh

add wrapper scripts for app-sre CI

---

Makefile

Forgot to remove the docker-login make target dependency

Fix errant make dependency for docker-login-and-push

---

Makefile
build_deploy.sh

We were not overriding properly

---

.golangci.yml

Add a larger timeout to golang ci tests

---

deploy/bundle/generate-csv-template.py

bundle template csv generator needs python3

---

deploy/bundle/Makefile
deploy/bundle/template/deploymentvalidationoperator.clusterserviceversion.yaml
deploy/openshift/deployment-validation-operator-olm.yaml
deploy/openshift/operator.yaml

We may want in the future to copy it to a repository that is more
community oriented, but for the moment this should make things work
properly with app-sre automation

Image pushes to quay.io/app-sre

---

pkg/controller/generic_reconciler.go

This is very handy to avoid generating metrics we're not going to use... I don't know if we were planning to do something fancier with config. This is nice and easy and it is exactly what we need 😂 

Add ability to ignore certain namespaces

---

hack/build_channel_catalog.sh

Dry run false by default in build catalog

---

hack/build_channel_catalog.sh

APP_SRE_BOT_PUSH_USER is not defined in app-sre CI/CD

Fix git clone credentials

---

deploy/bundle/template/deploymentvalidationoperator.clusterserviceversion.yaml

It contained only the version, not the operator name and version

Fix replaces field in CSV

---

hack/build_channel_catalog.sh

Fix GOOS and GOARCH mappings for grpcurl

---

.golangci.yml
Makefile

These will be run on top of what boilerplate offers. See https://github.com/openshift/boilerplate/pull/92

Run additional golangci checks

---

hack/app_sre_build_deploy.sh
hack/build_deploy.sh

Use build-push target

---

OWNERS

Added owners file

---

deploy/bundle/generate-csv-template.py

Use skip range

---

OWNERS

2uasimojo is a reviewer

---

hack/build_channel_catalog.sh

Fix bug in opm cmd name when building bundle

---

Makefile

Move to a common saas operator versions repo

---

Makefile
hack/build_channel_catalog.sh

I want the script to be copied in boilerplate with minimal changes, so here's some preparation
* We use ensure to install opm and build
* We use repo_root mechanism used in boilerplate
* Some editing in variable naming, to make them clearer

Prepare catalog script to be moved to boilerplate

---

Makefile
boilerplate/openshift/golang-osd-operator/standard.mk
hack/app_sre_build_deploy.sh

Build opm catalogs using boilerplate

---

Makefile

vars to be overriden before loading boilerplate

---

deploy/openshift/operator.yaml

Let's make it comply with its own standards :)

DVO operator should run with three replicas

---

boilerplate/openshift/golang-osd-operator/build-opm-catalog.sh

olm script is not pushing to versions repo

---

deploy/openshift/deployment-validation-operator-olm.yaml

Pass NAMESPACE_IGNORE_PATTERN to the deployment

---

boilerplate/openshift/golang-osd-operator/build-opm-catalog.sh

Do not wrap main in or condition

---

pkg/utils/object.go

only ignore deployment-like resources owned by deployment-like resources

---

OWNERS

I think I was on this list from when we were working on OPM builds.

Remove 2uasimojo from reviewers

---

deploy/observability/grafana-dashboard-dvo.yaml
deploy/observability/grafana.yaml

add Validation Detail panel

---

build_tag.sh

add build_tag

---

build_tag.sh

fix build tag

---

deploy/openshift/operator.yaml

update image repo

---

deploy/openshift/operator.yaml
pkg/validations/validation_engine.go

use default config if configmap does not exist

---

pkg/validations/validation_engine.go

use empty config path if config file does not exist

---

deploy/observability/grafana-dashboard-dvo.yaml

set instant to avoid fractions

---

deploy/openshift/network-policies.yaml
deploy/openshift/operator.yaml

This should fix DVO flagging itself with any failing checks.
Also fixes some apparent indent issues in `deploy/openshift/network-policies.yaml`.

Fix DVO checks against itself (dvo-22)

---

deploy/openshift/operator.yaml

default memory limit 512M -> 4GB
We'll probably want to template-ize this?

change default memory limit

---

pkg/controller/controller.go
pkg/utils/object.go

Fix Register Openshift Kinds in Kube Env.

fix: registering openshift kinds in kube env

---

README.md
deploy/openshift/operator.yaml

Changed DVO replica count to 1. Inputted kube-linter check to skip 3 minimum replica check on DVO's own replica count. Changed README to reflect 1 pod for deployment fix

Changed DVO replica count to 1 for DVO-37

---

README.md
docs/new-releases.md

Included a breakdown of steps to create a new release of DVO in README

Modified README to include steps for New Release

---

docs/checks.md

Checks.md appears with checks bunched together instead of vertical alignment. Need to fix for readability.

Fixing formatting of checks document

---

deploy/openshift/operator.yaml

Infra node mapping needs this tolerance added

Adding tolerance for infra nodes

---

hack/olm-registry/olm-artifacts-template.yaml

Fixing namespace from label section to metadata

Fixing service object

---

hack/olm-registry/olm-artifacts-template.yaml

Adding missing platform level NS to ignore patterns

Adding patterns for NS ignore

---

hack/olm-registry/olm-artifacts-template.yaml

Configmap needs to exist for 3 replica check to work

Adding configmap to fix 3 replica issue

---

.gitignore
pkg/controller/generic_reconciler.go
pkg/controller/watchnamespaces.go
pkg/utils/object.go
pkg/utils/request.go
pkg/validations/base.go
pkg/validations/base_test.go
pkg/validations/utils.go
pkg/validations/validation_engine.go

feat: adding namespace_uid and name_uid to metrics

---

hack/olm-registry/olm-artifacts-template.yaml

Merging this MR will deploy DVO V2 to the production AppSRE org.
This MR will be merged on Monday Oct 10th at 13:00UTC.

Deploy DVO V2 to AppSRE prod

---

pkg/controller/validationscache.go
pkg/controller/validationscache_test.go

Refactored Controller package : validationscache functionality
* added some documentation to functions
* refactored **objectAlreadyValidated** function to reduce cognitive complexity
* added unit tests for **objectAlreadyValidated** and **store** methods
https://issues.redhat.com/browse/CCXDEV-9722

Minor refactor on Controller package : validationscache

---

pkg/controller/generic_reconciler_test.go
pkg/controller/reconcileobjects.go
pkg/controller/reconcileobjects_test.go
pkg/controller/validationscache_test.go

* Added documentation for resourceSet exposed methods
* Added unit tests for GetPriorityVersion function
* Fixed previous unit tests documentation
* [CCXDEV-9722](https://issues.redhat.com/browse/CCXDEV-9722)

Add Reconcileobjects unit tests

---

hack/generate-operator-bundle-contents.py

The no-nodeAffinity option allows us to use the script to generate CSV files that can be used for OCP installations.
The other change regards the output-dir variable where previously, you'd have to have the output-dir previously created otherwise the script would fail.

Improve CSV generation script for OCP clusters

---

pkg/controller/generic_reconciler.go

I think the operator doesn't have to read API resources metadata in every reconciliation (since this will not change in runtime). I tried to do this in the reconciler constructor, but then it was crashlooping in larger clusters (I think the health probe didn't start in time).

read API resources metadata only once

---

.tekton/deployment-validation-operator-pull-request.yaml
.tekton/deployment-validation-operator-push.yaml

Fixing Konflux's tekton files to set default the source image building.

DVO-213: Konflux fix to set default image building

---

build/build_opm_catalog.sh
hack/olm-registry/olm-artifacts-template.yaml

* Migrate to file based catalog
* update
* add opm render command

Migrate to file based catalog (#388)

---

build/Dockerfile
go.mod
go.sum
konflux-ci/bundle/bundle.Dockerfile
konflux-ci/bundle/manifests/deployment-validation-operator.clusterserviceversion.yaml
konflux-ci/bundle/metadata/annotations.yaml

Updated some libraries that were triggering some errors on external validators

NO-JIRA: Update dependencies versions on some libraries

---

OWNERS

Add new team-members' GitHub users to the OWNERS file to enable them to review and approve PRs from now on.

NO-JIRA: Add new team members

---

renovate.json

Add Renovate (the tool used by konflux-bot) configuration to avoid PR duplicity and the extra noise and CI runs.
https://konflux.pages.redhat.com/docs/users/faq/general-questions.html#i-dont-want-konflux-to-update-my-dependencies-i-just-want-the-basics-how-can-i-do-that

NO-JIRA: Add configuration for konflux-bot

---

.tekton/images-mirror-set.yaml
konflux-ci/bundle/manifests/deployment-validation-operator.clusterserviceversion.yaml

Added definitive prod images reference to the mirrorset

DVO-213: Add Prod images reference to mirror-set and bundle

---

.tekton/images-mirror-set.yaml
konflux-ci/bundle/bundle.Dockerfile
konflux-ci/bundle/manifests/deployment-validation-operator.clusterserviceversion.yaml

Upgraded bundle release versions in the containerfile and the CSV
Updated operator images' digest with the last build

DVO-296: [release-0.7.12] Upgrade bundle image and CSV
