app-sre/deployment-validation-operator

deploy/bundle/Makefile, deploy/bundle/generate-csv-template.py, deploy/bundle/template/deploymentvalidationoperator.clusterserviceversion.yaml, deploy/openshift/cluster-role-binding.yaml, deploy/openshift/cluster-role.yaml, deploy/openshift/operator.yaml, deploy/openshift/role-binding.yaml, deploy/openshift/role.yaml, deploy/openshift/service-account.yaml
In this way we can use the manifests to install the operator without the
whole OLM infrastructure.
=> Generate CSV from separated manifest files

build/Dockerfile, cmd/manager/main.go, config/config.go, deploy/bundle/Makefile, deploy/bundle/template/deploymentvalidationoperator.clusterserviceversion.yaml, deploy/openshift/operator.yaml, go.mod, pkg/controller/generic_reconciler.go, pkg/controller/generic_reconciler_test.go, pkg/validations/base_test.go, pkg/validations/replicas_test.go, pkg/validations/requests_limits_test.go, pkg/validations/utils.go
While dv-operator is shorter, it does not tell anything about the
purpose of the operator. The convention of openshift operators is to
have long and descriptive names, so let's follow it.
=> Rename repo to deployment-validation-operator

Makefile, build/Dockerfile, build/Dockerfile.test
* Image is built through a multi-stage build to avoid depending on the
go interpreter from the environment
* Create a make target to test using a Docker to avoid depending on the
go interpreter from the environment
* Added a make target to login and push
=> Prepare for CI

Makefile
This is needed because docker needs to be logged into before generating
the image in order for the proper username to be included in the docker
image name
=> Add new target in Makefile for docker login

Makefile, build_deploy.sh
When creating an image, the org used when generating the image
name is defined by the USER env which is usually the username
running the command.  This isn't always the desired namespace for
things like CI/CD
=> Removed additional docker login make target and set user in build_deploy

deploy/bundle/Makefile, deploy/bundle/template/deploymentvalidationoperator.clusterserviceversion.yaml
The first time a bundle is built there will be no version to replace,
so need to make it optional and remove references to it in the CSV.
=> Make REPLACE_VERSION optional when generating the CSV for the bundle.

deploy/bundle/Makefile
If this isn't removed there are effectively 2 csvs in the manifest
dir, which isn't good
=> Remove the backup csv generated when removing replaces from the manifest

cmd/manager/main.go
It is not serving any metric, so unless it is used for something I don't understand I would remove it and just have one single metrics endpoint.
=> Remove Operator Metrics Server

boilerplate/openshift/golang-osd-operator/standard.mk, build_catalog.sh, deploy/bundle/Makefile, deploy/bundle/template/deploymentvalidationoperator.clusterserviceversion.yaml
The bundle was being generated with the incorrect operator image
tag which causes a failure in catalog generation.  Since latest
tag is used that tag can not be pushed unless bundle and catalog
generation succeed.  Also changed the bundle/catalog env names to
be more consistent with other names for images
=> Fixes to catalog/bundle generation

Makefile
This was removed in 979e8c8 when we updated boilerplate
=> Use vendor directory

deploy/bundle/generate-csv-template.py, deploy/bundle/template/deploymentvalidationoperator.clusterserviceversion.yaml, deploy/openshift/deployment-validation-operator-olm.yaml, hack/app_sre_build_deploy.sh, hack/build_channel_catalog.sh
Yesterday we met with the OLM team and the introduced us the `semver` approach. It seems good at first sight for us, however there are two things that we can't fix with the `semver` approach:
- The appeal of using `semver` is that you don't need to store state, you only need to fetch the latest index image and add a new bundle to it. However, we still need state in order to be able to rebuild the index image in a disaster event in the container registry.
- If we use `semver` we can't easily skip a faulty version. Let's say we find a bundle to be faulty. In this scenario we want to ensure that the next time we build a bundle it jumps over the fault version. The `skips` parameter is ignored in the `semver` mode. Maybe we could use `skipRange` (which is respected at runtime in `semver` …
=> Proposal single channel

boilerplate/openshift/golang-osd-operator/build-opm-catalog.sh
Fixing line 337: skip_versions[*]: unbound variable
=> Initialize skip versions if it doesn't exist

Makefile
TIL if you do this:
```make
foo:
do_a_thing
foo: bar
```
...the "override" doesn't actually stop the original `foo` from running. So the above will actually run `bar` and then `do_a_thing`.
You have to give the override substance. So:
```make
foo:
do_a_thing
foo: bar
do_a_different_thing
```
...will run `bar` and then `do_a_different_thing`.
In our case we actually want to *replace* `foo` with `bar` so we have to give the override "no-op" substance, which looks like this:
```make
foo:
do_a_thing
foo: bar ;
```
(note the semicolon)
This will *just* run `bar` when `make foo` is invoked.
=> Override `build-push` properly

pkg/validations/base.go, pkg/validations/validation_engine.go
The problem to solve is two-fold:
1. Original implementation was setting 0 to clear metrics, generating a LOT of metrics for passed validations
2. Original implementation was resetting all labels for a metric before processing the results.  This would cause metric flapping for failed validations
This change attempts to handle the above intelligently.  When clearing the metrics, it will delete the labels from a metric if that metric is not in the list of failed checks returned by kube-linter.  Then the processing of the results continues as before, setting a metric for each failed validation.
=> Delete metrics for validations not in the report from kube-linter

pkg/validations/base_test.go, pkg/validations/validation_engine.go
This will force DVO to disable kube-linter checks that don't work correctly in DVO. Also adds a test.
=> Disable incompatible checks

pkg/validations/base.go, pkg/validations/base_test.go, pkg/validations/gen.go, pkg/validations/utils.go, pkg/validations/validation_engine.go, tools.go
(DVO-12)
Adds "check_description" and "check_remediation" as constant labels for check-validation metrics.
Prints out "check_description", "check_remediation", and "check_failure_reason" in logs.
Changes the "Help" string for metrics to include both a description and remediation.
Modifies a test to validate that metrics include the constant labels.
The validationEngine struct now stores `map[string]config.Check` for all registered checks, because I couldn't find any better way for `RunValidations()` to get access to kube-linter check descriptions.
=> "check_description" and "check_remediation" labels for metrics

pkg/validations/base_test.go
When creating new custom checks within the validations package, if validation engine gets initialized  more then once, GO will throw a panic error. This is work set to remedy this issue.
=> Refactoring initializing engine due to new custom check conflicts

pkg/validations/base.go, pkg/validations/base_test.go
Added condition where no validations are run and metrics cleared if object is found to have replica count of 0
=> Check to clear metrics if 0 replicas

pkg/controller/generic_reconciler.go
This MR fixes bug [DVO-31](https://issues.redhat.com/browse/DVO-31): Deleted Namespace and Kind still show in DVO grafana / prometheus.
Reconcile watches objects and triggers validations.RunValidations(), where DVO output is shipped to DVO's /metrics endpoint. Delete metric labels operations are also handled in RunValidations(). 
On deletion, gvk.Kind is an empty string for all resource types besides "Pod". This string is passed into RunValidations and is used to construct the prometheus labels for the associated metric.
When a deletion event is passed to RunValidations for non-pod resources (Deployment, ReplicaSet),  promLabels is missing the kind field, and as such can't associate the provided deletion event with the existing metrics. For an example nginx deployment, the prom labels do …
=> Ensure metrics are deleted for resources in a deleted namespace

cmd/manager/main.go, pkg/controller/generic_reconciler.go, pkg/prometheus/prometheus.go, pkg/validations/base_test.go, pkg/validations/validation_engine.go
Currently, DVO's `/metrics` endpoint exposes a great number of metrics, including those of the default prometheus go-client collectors, as well as metrics managed by the controller-runtime package.
This PR disables the `/metrics` endpoint managed by controller-runtime, and replaces it with a default and more minimal promhttp handler. In addition to the failing-validation metrics, this will cause DVO to expose only a few dozen non-validation metrics (e.g. goroutines, cpu, memory, http requests handled, etc) about DVO itself (as opposed to thousands of additional controller-runtime-managed metrics).
Prometheus-setup code is added to its own new package. This package manages the global Prometheus registry(which used to managed by controller-runtime).
Testing this on the app-sre-stage-01 …
=> expose minimal prometheus metrics (DVO-23)

README.md
Nod to upstream in README file.
=> Adding info about upstream

deploy/observability/template.yaml
Current prometheus operator deploys 2 replicas and naming is confusing. Changing to 1 replica and altering naming convention.
=> Altered prometheus operator to 1 replica and changed naming

deploy/openshift/operator.yaml
DVO should implement best practices it itself recommends.
since DVO's main function is to provide metrics related to DVO violations, IMO it makes sense to use the metrics endpoint as an indicator for readiness and health.
=> add probes to deployment

hack/olm-registry/olm-artifacts-template.yaml
**What**
Created an initial olm artifacts template based on what I can infer from the olm artifacts template in addon-operator.
**Why**
App-interface saas file will need to refer to this template file in order to create a selectorsyncset in hive.
I'm new at DVO and the hive/olm/app-interface deployment model/processes so I may have naively created this template in that case please let me know. I partially tested dvo deployment on a local kind cluster with olm and used another hive kind cluster to test the SS.
=> Iniital olm artifacts template

hack/olm-registry/olm-artifacts-template.yaml
Adding network policy to allow ingress from only the openshift insights operator. Also added namespace pattern exclusions to not have DVO alert on platform level stuff to customer.
=> Adding network object for insight operator and namespace pattern ignore

deploy/openshift/operator.yaml
Quick change to ensure OSD rollout of DVO accounts for all namespaces to ignore to ensure customer does not receive platform related recommendations
=> Added namespaces to ignore for platform

hack/olm-registry/olm-artifacts-template.yaml
This adds in additional restrictions to the rollout of DVO:
- Only roll out to clusters 4.11+
- Only roll out to clusters in the staging and integration environments
=> Restrict rollout of SSS

deploy/openshift/operator.yaml
Adding node selector to assure DVO is deployed on infra nodes for OSD deployment
=> Adding infra-node to assure operator deploys on infra node

hack/olm-registry/olm-artifacts-template.yaml
Using https://olm.operatorframework.io/docs/advanced-tasks/unsafe-fail-forward-upgrades/#using-unsafefailforward-upgrades, so we can exit from a failed CSV in a fleet-wide event, just by releasing a new version.
=> OLM can now upgrade even if the CSV fails

hack/olm-registry/olm-artifacts-template.yaml
Previous object was being rejected with this message
```
for: "object": OperatorGroup.operators.coreos.com "deployment-validation-operator-og" is invalid: [spec.upgradeStrategy: Invalid value: "object": spec.upgradeStrategy in body must be of type string: "object", spec.upgradeStrategy: Unsupported value: map[string]interface {}{}: supported values: "Default", "TechPreviewUnsafeFailForward"]')
```
=> fix updateStrategy

pkg/controller/generic_reconciler.go, pkg/controller/reconcileobjects.go
Add a check to ensure that an APIResource (gvk) supported by the server is registered in the client-go scheme
Add a mechanism to make sure that the gvk of the APIResource is chosen based on what is supported by client scheme when server supports more than one version.
eg: server supports `batch/v1/CronJobs` and `batch/v1beta1/CronJob` but client knows only about 
`batch/v1beta1/CronJob`. In this case `batch/v1beta1/CronJob` will be used in queries.
Signed-off-by: Nikhil Thomas <nikthoma@redhat.com>
=> Improve apiResource listing mechansim for deciding resources to be validated

hack/olm-registry/olm-artifacts-template.yaml
This ensures that clusters need to be 4.11.10+ to get DVO.
=> Restrict deploying DVO to clusters that are 4.11.10+

boilerplate/_data/last-boilerplate-commit, boilerplate/openshift/golang-osd-operator/build-opm-catalog.sh
Conventions:
- openshift/golang-osd-operator: Update ---
https://github.com/openshift/boilerplate/compare/f1ce2ebcab3cd03ddb7c46d1c8c96a810d5d5ca1...2bdc59eec75cc9dcd03c2d790e7bea9138579ce7
commit: 94825f3cf075658be2cac702c0b64e6f037ef7c4
author: Andrew Pantuso
fix: fix opm-build-push to use proper container engine name
=> Boilerplate: Update to 2bdc59eec75cc9dcd03c2d790e7bea9138579ce7

OWNERS
* Adds Tomas Remes and Ricardo Lüders, from CCX team, as approvers/reviewers to facilitate ownership transfer
=> Add CCX members suitable to maintain the project in the future

OWNERS
* Adding Joao Fula, member of ccx team, to approvers and reviewers list
=> Add ccx member to reviewers/approvers owners list

go.mod, pkg/controller/generic_reconciler.go, pkg/controller/generic_reconciler_test.go
* Removed code that processed cluster-wide resources
* Removed unexported methods associated to that code
* Add unit test to fixed method
* Minor refactor on how the namespaced resources are processed
https://issues.redhat.com/browse/DVO-102
=> Exclude cluster scoped resources from KubeLinter analysis

pkg/controller/validationscache.go, pkg/controller/validationscache_test.go
Two deployments with the same name and in the same namespace have to be cached separately.
=> DVO-107: cache key has to include resource UID

pkg/validations/base.go
Previously it was logged as `"kind": "&TypeMeta{Kind:Deployment,APIVersion:apps/v1,}"`, but we want to have `"kind": "Deployment"`
=> minor logging fix

pkg/controller/generic_reconciler.go, pkg/controller/generic_reconciler_test.go, pkg/utils/app_label.go, pkg/utils/app_label_test.go
DVO tries to group objects with the same app label value. Before this update, the operator tried to read the following paths to get the app label value:
- `metadata.labels.app`
- `spec.selector.matchLabels.app`
The problem with this approach is that labels can match using matchExpressions. An example is:
```
key: app
operator: NotIn
values:
- foo
- bar
```
which means match everything except of resources with app=foo or app=bar. This is a more effective approach but more complex.
The problem is that we don't know the set of app label values (in a namespace) in advance. So the logic here is to sort the found `GroupVersionKinds` according their group (this adds the `apps/v1` group between the first in the slice) and then process the `app` label selectors.
=> DVO-105: extends the logic of matching "app" labels

deploy/openshift/deployment-validation-operator-olm-with-polling.yaml, deploy/openshift/deployment-validation-operator-olm.yaml, hack/olm-registry/olm-artifacts-template.yaml
* Restricted SCC enforcement will be added with OCP 4.14
* Updating the catalogsource to allow the operator to get deployed
* Clusters that don't support the setting (<4.12) will ignore it
Jira: [OSD-15625](https://issues.redhat.com//browse/OSD-15625)
=> Make catalogsource compatible with restricted SCC enforcement

pkg/controller/generic_reconciler.go, pkg/controller/generic_reconciler_test.go, pkg/utils/app_label.go, pkg/utils/app_label_test.go
namespace
If the resource has empty "selector" defined then it matches all the objects in the corresponding namespace.
=> DVO-132: empty selector matches all the resource in the corresponding

README.md, deploy/openshift/configmap.yaml, deploy/openshift/deployment-validation-operator-olm.yaml, hack/olm-registry/olm-artifacts-template.yaml, pkg/validations/validation_engine.go
If no custom configuration is found, the project will now whitelist the checks monitored by Rules Team by default.
* yaml files containing default configuration data (in case they're used out of the box)
* Updated documentation with default configuration info
=> DVO-131: Fix default configuration with already watched rules 

bundle.Dockerfile, bundle/manifests/deployment-validation-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, deploy/openshift/operator.yaml, main.go, pkg/configmap/configmap_watcher.go, pkg/configmap/configmap_watcher_test.go, pkg/controller/configmap_watcher.go, pkg/controller/generic_reconciler.go, pkg/controller/generic_reconciler_test.go, pkg/prometheus/prometheus.go, pkg/validations/base_test.go, pkg/validations/utils.go, pkg/validations/validation_engine.go, pkg/validations/validation_engine_test.go
* Allow the project to change the configuration in execution time, updating the validations with the new configuration updated on the ConfigMap
=> DVO-111: Dynamic validation engine

pkg/controller/generic_reconciler.go, pkg/controller/generic_reconciler_test.go, pkg/utils/selector.go, pkg/utils/selector_test.go
This fixes:
-  the sorting of GVKs - we want to sort the resources by `Kind` in the same `Group`. 
- reading the `selector` for `v1.Service` and `v1.ReplicationController` when the `selector` is defined as `map[string]string` instead of `metav1.LabelSelector`
=> DVO-145: Fix parsing selectors & labels for v1.Service and others

pkg/controller/validationscache.go, pkg/controller/validationscache_test.go
I also added simple benchmark test filling the validation cache/map, removing all the items and filling it again. 
I don't provide the numbers here, bu they are speaking rather for the pointer version.
=> validation cache/map - use pointer to safe few bytes

pkg/validations/test-resources/config-with-some-excluded-checks.yaml, pkg/validations/utils.go, pkg/validations/validation_engine.go, pkg/validations/validation_engine_test.go
Now when the config with `include` is in place, there's no need to disable any incompatible checks.
=> remove unnecessary disabling of incompatible checks

pkg/configmap/configmap_watcher.go, pkg/controller/generic_reconciler.go, pkg/validations/validation_engine.go
* Fix current Watcher channel to work with an empty struct
* Add configuration property on watcher struct
* Add new method to retrieve configuration from Watcher
* Add new method to Validation Engine (and interface) to deliver enabled checks
* Add logline with collection of enabled checks when the configuration is updated
```
INFO	reconcile	Current set of enabled checks	{"checks": "run-as-non-root, unset-memory-requirements"}
```
=> DVO-142: improve watcher channel comms

pkg/controller/generic_reconciler.go
This is adding two following things:
- removing `managedFields` from the validated objects (to save somer memory)
- add namespace name info in reconciliation logging
=>  minor memory and logging improvement

pkg/controller/generic_reconciler_test.go, pkg/validations/validation_engine_test.go
Fixes this message:
```
pkg/validations/validation_engine_test.go:261:31: G601: Implicit memory aliasing in for loop. (gosec)
deployment.Spec.Replicas = &tt.updatedReplicaCount
^
pkg/validations/validation_engine_test.go:275:32: G601: Implicit memory aliasing in for loop. (gosec)
deployment.Spec.Replicas = &tt.initialReplicaCount
^
```
=> style: fixing gosec implicit memory for tests

bundle/manifests/deployment-validation-operator.clusterserviceversion.yaml, deploy/openshift/deployment-validation-operator-olm.yaml, deploy/openshift/operator.yaml, hack/olm-registry/olm-artifacts-template.yaml
* Exclude resources whose namespaces are based on `open-cluster-management` prefix
=> DVO-173: Update deployments exclude patterns

pkg/controller/generic_reconciler.go
kubelinter validations don't seem to require 'status' attribute of the objects
=> DVO-178: remove status from the validated objects

pkg/controller/generic_reconciler.go, pkg/controller/generic_reconciler_test.go, pkg/controller/validationscache.go, pkg/controller/validationscache_test.go
Basically, the original object's namespace ID is now included as part of the cache key. This ensures that when the code finishes and starts deleting non-existent objects, it successfully recognises the past objects and then removes the metrics associated with them.
Previously, the namespace ID for these objects was captured by the currently recreated namespace. This way there was no way for the code to remove metrics created with the previous namespace ID, even if it recognised the objects as removable.
* Changed some function signatures to make the current namespace ID handle cache keys correctly.
* Changed existing unit tests using these functions to work properly with the new signature
* Minor fixes due to linting
* Addition of new unit test for this specific case (recreated …
=> DVO-185: bugfixed persisting metrics after namespace recreation

.golangci.yml, internal/testing/client.go, pkg/prometheus/prometheus.go
This PR replaces the deprecated `golint` with `revive` and fixes some code style issues reported by it.
=> DVO-205: (chore) replace golint

pkg/controller/const.go, pkg/controller/generic_reconciler.go
When DVO is installed in a cluster with no namespaces to validate, the code in reconcile packages loops so fast that GC does not have time to address everything. This apparently causes CPU usage to grow up to the set limit.
This fix checks the namespaces to validate before triggering the logic in the `reconcileEverything` function. If there is no namespace to validate, it just waits a bit and skips the loop.
=> DVO-209: CPU leak fix

Makefile
https://ci.int.devshift.net/view/deployment-validation-operator/job/app-sre-deployment-validation-operator-gh-build-master is failing because of 
```
16:00:17 boilerplate/openshift/golang-osd-operator/build-opm-catalog.sh: line 246: python: command not found
```
this is an attempt to fix or at least workaround
=> DVO-224 trying to fix failing build

hack/olm-registry/hypershift-template.yaml
Deployment on Hypershift hosted clusters is inspired by the deployment of the metrics-forwarder config.
As you can see, the `PlacementRule` has evolved for this config:
https://github.com/openshift/hypershift-dataplane-metrics-forwarder/pull/52/files
(more details in [OSD-21462](https://issues.redhat.com/browse/OSD-21462))
We should no longer ignore `ManagedCluster`s (objects at service cluster level) for which the `ManagedClusterConditionAvailable` condition is not "true"
=> OSD-24739 / DVO-223: Making sure DVO is deployed/updated on all hosted clusters

go.mod
* Downgraded toolchain to maximum allowed version by CPaaS
=> DVO-225: CPaaS Image builder requires <1.22.5 toolchain

Makefile, build/build_opm_catalog.sh
* Script scope was using wrong set of credentials to log in to image registry
* Sent env vars with the creds from the Makefile
* Set the command as hidden to avoid leaking creds in the job's output
=> DVO-228: Move registry login to script

.tekton/deployment-validation-operator-push.yaml
Konflux CI pipeline deployment-validation-operator on-push is failing. This fix should work removing a deprecated dependency. This was not saw on the previous Update references' PR from Konflux.
=> NO-JIRA: Remove deprecated reference to JAVA dependency

hack/olm-registry/hypershift-template.yaml
This is causing a PodSecurityViolation leading to DVO not running on HCP clusters
```
Status:
Message:  couldn't ensure registry server - error ensuring pod: : error creating new pod: deployment-validation-operator-catalog-: pods "deployment-validation-operator-catalog-7wq6g" is forbidden: violates PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "registry-server" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "registry-server" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "registry-server" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "registry-server" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost") …
```
=> SDCICD-1436: set securityContextConfig restricted

konflux-ci/release-snapshot.yaml, konflux-ci/release-staging.yaml
Added some manifests to be used on the Konflux CLI to help releasing a new version (currently only staging)
=> DVO-213: add staging manifests

go.mod
Bump Golang version now that the builder image was upgraded
=> NO-JIRA: Bump Golang to 1.23

.ci-operator.yaml
This PR aims to fix the error from CI
`go: golang.org/x/sys@v0.31.0 requires go >= 1.23.0 (running go 1.22.9; GOTOOLCHAIN=local)
make: *** [Makefile:30: go-mod-update] Error 1
{"component":"entrypoint","error":"wrapped process failed: exit status `
So we need to update the Golang version inside `.ci-operator.yaml` to `1.23`
Reference link: https://redhat-internal.slack.com/archives/G019KPS1S6R/p1745256764181379
=> Update the Golang version of .ci-operator.yaml

.tekton/deployment-validation-operator-fbc-pull-request.yaml, .tekton/deployment-validation-operator-fbc-push.yaml, .tekton/images-mirror-set.yaml, konflux-ci/bundle/manifests/deployment-validation-operator.clusterserviceversion.yaml, konflux-ci/staging-release.yaml, konflux-ci/staging-snapshot.yaml
Add ImageDigestMirrorSet manifest to link Konflux images with future registry images' links
* Some refactoring on the manifests for Snapshot and Release
* Added missing FBC task for FIPS on Konflux pipeline
=> DVO-213: Add ImageDigestMirrorSet links

.tekton/images-mirror-set.yaml, konflux-ci/bundle/bundle.Dockerfile, konflux-ci/bundle/manifests/deployment-validation-operator.clusterserviceversion.yaml, konflux-ci/cli-manifests/prod-release.yaml, konflux-ci/cli-manifests/prod-snapshot.yaml, konflux-ci/cli-manifests/staging-snapshot.yaml
Adding last manifests for Prod releases
Fixing some paths with outdated versions
=> NO-JIRA: Fix outdated versions and Prod manifests

.tekton/dvo-fbc-ocp4-18-pull-request.yaml, .tekton/dvo-fbc-ocp4-18-push.yaml, konflux-ci/fbc/catalog.Dockerfile
* The catalog's Dockerfile was fixed to accept build-arg parameters. Specifically, it was changed so that the image used would be a concrete OCP version.
* Fixed the tekton files for the Konflux pipeline for this FBC (OCP 4.18)
=> DVO-285: Fix Konflux pipeline for the FBC for OCP 4.18

build/Dockerfile
Apparently `dependabot` introduces by error a duplication on the version release for the images we use on the Dockerfile
Merging here #529
=> NO-JIRA: Fix images typos from dependabot

go.mod
Fixes CVE-2025-22871 with a Golang version +1.23.8
=> DVO-283: Update minimum Golang version

konflux-ci/fbc/bundle.object/catalog/deployment-validation-operator/catalog.yml, konflux-ci/fbc/csv.metadata/catalog/deployment-validation-operator/catalog.yml
Operator image's digest is mandatory in the catalog fragments on Konflux
=> Add missing digest to operator image

.tekton/images-mirror-set.yaml, konflux-ci/bundle/manifests/deployment-validation-operator.clusterserviceversion.yaml
Fix bundle labels to use with the new multi-arch
=> DVO-294: Fix bundle for multi-arch

build/Dockerfile
For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Ralph Bean <rbean@redhat.com>
Assisted-by: Gemini
=> chore(KONFLUX-6210): fix and set name and cpe label for deployment-validation-operator
